# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        name: Trailing Whitespace
    -   id: end-of-file-fixer
        name: End of File Fixer
    -   id: check-yaml
        name: Check Yaml
    -   id: check-added-large-files
        name: Check Added Large Files
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        language: python
        entry: .venv/bin/flake8
        types: [file, python]
-   repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/bin/black
        language: python
        language_version: python3.11
        types: [file, python]
